### PR TITLE
Fix `clippy::all` warnings in `substrate`

### PR DESCRIPTION
**Pull request by rockbmb**
@geigerzaehler WIP, we may decide it's not at all worth it to keep `clippy::all` in CI.

### CODE REVIEW

**Comment by geigerzaehler** [comment]
I think it only makes sense to enable clippy for the `substrate` code base if they merge these fixes upstream and commit to use it upstream. Otherwise we are in a position where we need to maintain our fixed fork and fix their lints.

To check only our packages we should run `clippy` without the `--all` flag and select our packages explicitly with `-p`.

**Comment by geigerzaehler** [comment]
> To check only our packages we should run `clippy` without the `--all` flag and select our packages explicitly with `-p`.

Turns out that this does not work. Investigating further...

**Comment by rockbmb** [comment]
@geigerzaehler I forgot to mention this - as part of this PR I intend to submit these changes upstream, and request that `clippy` be added to their CI pipeline.

I saw that in this repo there's a `ci-test-lint` branch where you try out `clippy -D clippy::all`, so I thought I'd try adding that here as well.

**Comment by geigerzaehler** [comment]
@rockbmb Can we delay merging this PR until the changes are merged upstream? For now I’d prefer to disable clippy instead of having to maintain a fork of substrate.

**Comment by rockbmb** [comment]
@geigerzaehler ✔️

**Comment by rockbmb** [comment]
#18 makes this redundant.

**Pull request closed without merging**
