### PR TITLE
Return block number when sending message

### PR DESCRIPTION
**Pull request by CodeSandwich**
Fixes https://github.com/radicle-dev/radicle-registry/issues/285

### CODE REVIEW

**Comment by CodeSandwich** [comment]
> Looks good overall, my only remark is to rename `number` to `block_number`.

Good idea :+1:

> We could also group the block-related fields in a `BlockInfo` or some type alike that would have `hash` and `number`. Not important now.

While I agree that it would add some value, it would also make this change a breaking one for the API.

**Comment by NunoAlexandre** [comment]
> While I agree that it would add some value, it would also make this change a breaking one for the API.

Yeah, it adds no value at the moment, but probably a good idea if we add a 3rd block-related field to it.

**Comment by xla** [comment]
> Fixes #285

It doesn't entirely address the issue as we still need the ability to get the current height.

**Comment by CodeSandwich** [comment]
> Using `number` instead of `height` doesn't really match the expectation of the domain. Never seen it to be referred to anything but the `height`. Is there a particular reason we call it differently?

That's a Substrate naming convention. I find it confusing and would rather use `height`, but having two names would be worse.

**Comment by xla** [comment]
> That's a Substrate naming convention. I find it confusing and would rather use `height`, but having two names would be worse.

Having substrate dictate our public API seems rather odd, I'd push to find what makes sense for our (`radicle Registry`) domain understanding and if this is `height` use that.

**Comment by CodeSandwich** [comment]
> It doesn't entirely address the issue as we still need the ability to get the current height.

Ouch, sorry about that. Could you respond to this comment? https://github.com/radicle-dev/radicle-registry/issues/285#issuecomment-604317880 This way we can discuss a proper solution.

**Comment by CodeSandwich** [comment]
> Having substrate dictate our public API seems rather odd, I'd push to find what makes sense for our (`radicle Registry`) domain understanding and if this is `height` use that.

@geigerzaehler Has it ever been discussed? If not, that's very much worth settling.

The ugly part is that this particular naming convention may have already leaked through type names, e.g. `BlockNumber`.

**Comment by xla** [comment]
> Ouch, sorry about that. Could you respond to this comment? [#285 (comment)](https://github.com/radicle-dev/radicle-registry/issues/285#issuecomment-604317880) This way we can discuss a proper solution.

Followed up there, but I think it that comment isn't concerned with fetching the current chain height.

**Comment by geigerzaehler** [comment]
> > Having substrate dictate our public API seems rather odd, I'd push to find what makes sense for our (`radicle Registry`) domain understanding and if this is `height` use that.
> 
> @geigerzaehler Has it ever been discussed? If not, that's very much worth settling.
> 
> The ugly part is that this particular naming convention may have already leaked through type names, e.g. `BlockNumber`.

We haven’t discussed this yet. There’s at least one other instance where there’s a mismatch in terminology: “extrinsic” vs “transaction”. In that case we’re also using the more common term “transaction” over the substrate specific “extrinsic”.

I think in general we should lean towards the more common terms in our public APIs. This might of course create a mismatch of terms in our code base but it’s easier to make this clear to the developers than to the consumers.

**Pull request closed without merging**
