### PR TITLE
Add clippy to Buildkite pipeline

### PR DESCRIPTION
**Pull request by rockbmb**

### CODE REVIEW

**Comment by rockbmb** [comment]
@geigerzaehler it seems using `--exclude substrate-subxt` allows `clippy` to ignore the client library, whereas locally the behavior I got was a little different.

Can you take a quick look at this?

**Comment by geigerzaehler** [comment]
> @geigerzaehler it seems using `--exclude substrate-subxt` allows `clippy` to ignore the client library, whereas locally the behavior I got was a little different.

I think clippy passes because all subxt issues were fixed. As I said I’m a bit reluctant to merge this with all the changes to subxt because it will make it harder to backport upstream patches.

**Comment by rockbmb** [comment]
@geigerzaehler oh wait, I must have been distracted - yes, that is indeed the case...
Let me roll back those changes.

**Comment by rockbmb** [comment]
Stale :moldy-bread:

**Pull request closed without merging**
