### PR TITLE
Version the state

### LINKED ISSUE #496: Version the state
Every piece of data in the state must be versioned, preferably as an enum. See [this thread](https://radicle.community/t/cli-runtime-compatibiliy/221/2).

### PR DESCRIPTION
**Pull request by CodeSandwich**
Fixes #496. Will squash when accepted.

### CODE REVIEW

**Comment by geigerzaehler** [comment]
This includes only the already reviewed PRs #515 and #519, right? Then this wouldn’t require a thorough review.

**Comment by NunoAlexandre** [comment]
@CodeSandwich I would actually prefer to keep the commit history. Just sayin'

**Comment by CodeSandwich** [comment]
@geigerzaehler Yes, sorry that I haven't warned about it. It's a wrap-up of these 2 PRs with a spec version bump.

**Comment by CodeSandwich** [comment]
@NunoAlexandre Ok, I'll keep it, it's fine by me :)

**Pull request merged**
