### PR TITLE
Add CI check to forbid fixup commits on pull requests

### PR DESCRIPTION
**Pull request by geigerzaehler**
Add CI check to forbid commits that start with "fixup!" in pull requests

### CODE REVIEW

**Comment by CodeSandwich** [comment]
Our workflow usually involves pushing without force a few fixup commits to take into account review comments. This change will make the CI always failing and red for the whole review duration except before it starts (vanilla commits) and after it ends (squashed commits).

This check also helps only if a strict `fixup` commit naming convention is followed.

If this is merged, my incentive will be to never use `fixup` in commit names to prevent false positives in CI.

**Comment by NunoAlexandre** [comment]
What motivates this, @geigerzaehler?

**Comment by CodeSandwich** [comment]
> What motivates this, @geigerzaehler?

I think that it's a reminder to squash.

**Comment by geigerzaehler** [comment]
This doesn’t work yet since our CI does not pass the base branch environment variable correctly to the build script.

> What motivates this, @geigerzaehler?

The fact that we sometimes forget to squash fixup commits: `git log origin/master --format=%s | grep fixup`.

> This change will make the CI always failing and red for the whole review duration except before it starts (vanilla commits) and after it ends (squashed commits).

It only marks the check `buildkite/radicle-registry/check-fixup-commits ` as failed. Does this change your view?

**Comment by CodeSandwich** [comment]
> It only marks the check buildkite/radicle-registry/check-fixup-commits as failed. Does this change your view?

Only a little. It still requires a strict naming convention and produces noise in the CI results. I think that the list of commits should be reviewed before hitting the merge button anyway.

**Comment by NunoAlexandre** [comment]
I agree with @CodeSandwich.

The thing I see is that if we have a PR with:

- Add X
- fixup! Y
- Add Z

this will still make its way into master, or not?

**Comment by geigerzaehler** [comment]
Since there’s no strong support for this and the benefits are likely marginal I’ll close this.

**Pull request closed without merging**
